Repository mrPronin/rc-ua, pull requests merged in 2023-12, with the labels that each got.

#30 API-SERVER Deploy to CapRover
  README.md
  captain-definition-api
  strapi/README.md
Labels: size/S

#29 Zustand store
  web-client/package-lock.json
  web-client/package.json
  web-client/src/App.tsx
  web-client/src/components/LanguageSelect/index.tsx
  web-client/src/components/MainLayout/index.tsx
  web-client/src/components/StyledComponents/FlexBox.tsx
  web-client/src/hooks/useMobileSize.ts
  web-client/src/hooks/useModal.ts
  web-client/src/intl/en.json
  web-client/src/intl/index.ts
  web-client/src/intl/ua.json
  web-client/src/main.tsx
  web-client/src/routes/appRoutesMap.tsx
  web-client/src/store/bloodCenters.ts
  web-client/src/store/settings.ts
  web-client/src/store/useBloodCenter.ts
  web-client/src/store/useBloodCenters.ts
  web-client/src/store/useSettings.ts
  web-client/src/view/BloodCenters/CenterDetails/index.tsx
  web-client/src/view/BloodCenters/index.tsx
  web-client/tsconfig.json
  web-client/vite.config.ts
Labels: size/XL

#31 Graphql cors
  api-server/src/api/app.py
  web-client/src/main.tsx
  web-client/src/view/BloodCenters/index.tsx
Labels: size/M
